Auth 2
MikeSIOO/kotlin-team pull request #17
Opened 2023-04-23 15:25 UTC by DionisSerbin

2023-04-24 04:55 UTC, MikeSIOO requested changes
Мы решили что не будем это в гите хранить

2023-04-24 04:55 UTC, MikeSIOO commented on app/google-services.json
Удали этот файл

2023-04-24 04:55 UTC, MikeSIOO commented on app/src/androidTest/java/com/example/kotlinTeam/ExampleInstrumentedTest.kt
И все тесты

2023-04-24 04:55 UTC, MikeSIOO commented on app/src/test/java/com/example/kotlinTeam/ExampleUnitTest.kt
Эти тоже

2023-04-24 16:45 UTC, denisdolgopolov requested changes

2023-04-24 16:45 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/authentication/presentation/view/SignUpFragment.kt
> +                if (firebaseAuthViewModel.signUp(requireContext(), email, pass, confirmPass)) {
лучше придерживаться везде однородной системы эмиттер-подписчик

то есть у экрана есть какой-то начальный стейт, в котором описано, что авторизация не прошла

после нажатия на кнопку, данные уходят во вьюМодел, там что-то происходит, и после этого меняется состояние экрана

при этом состояние экрана хранится как data-класс во MutableLiveData во ViewModel 

например, `val screenState = MutableLiveData<SignUpFragmentState(val isSignIn: Boolean = false)>`

2023-04-28 12:13 UTC, denisdolgopolov approved these changes

2023-05-03 10:00 UTC, MikeSIOO approved these changes

2023-05-08 14:14 UTC, merged