add made recipe to firestore user document and reload made recipes re…
MikeSIOO/kotlin-team pull request #27
Opened 2023-05-15 18:55 UTC by dddudKill

…cycler view

2023-05-16 06:31 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/feed/domain/useCase/SaveMadeRecipeUseCase.kt
> +    suspend operator fun invoke(recipeId: String) = withContext(Dispatchers.IO) { repository.saveMadeRecipe(recipeId, authRepository.getCurrentUser()!!.uid) }
а если авторизация слетела по какой-либо причине?)


лучше проверка на null и если что вернуть null/ошибку/пустое значение

2023-05-16 06:33 UTC, denisdolgopolov requested changes

2023-05-16 06:33 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/feed/presentation/FullRecipeFragment.kt
> +            viewModel.saveMadeRecipe(viewModel.currentRecipeState.value.currentRecipe!!.id!!)
а если null?)

2023-05-16 06:33 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/profile/presentation/ProfileFragment.kt
> -        viewLifecycleOwner.lifecycleScope.launchWhenStarted {
почему отказался от launchWhenStarted?

2023-05-16 06:33 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/profile/presentation/ProfileViewModel.kt
> +                getRecipes()
get...() что-то возвращает, судя по названию

а если нет, то лучше load..() или init...()

2023-05-17 13:44 UTC, dddudKill commented on app/src/main/java/com/example/kotlinTeam/feed/presentation/FullRecipeFragment.kt
> +            viewModel.saveMadeRecipe(viewModel.currentRecipeState.value.currentRecipe!!.id!!)
Поменял, что теперь кнопка недоступна в случае если рецепт нулл. По хорошему этот фрагмент показываться вообще не должен, если рецепт нулл

2023-05-17 13:45 UTC, dddudKill commented on app/src/main/java/com/example/kotlinTeam/profile/presentation/ProfileFragment.kt
> -        viewLifecycleOwner.lifecycleScope.launchWhenStarted {
Deprecated in java, поменял на то, что предлагали repeatOnLifecycle(Lifecycle.State.STARTED) {...}

2023-05-17 15:28 UTC, denisdolgopolov requested changes

2023-05-17 15:28 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/feed/domain/useCase/SaveMadeRecipeUseCase.kt
> +        withContext(Dispatchers.IO) { repository.saveMadeRecipe(recipeId, authRepository.getCurrentUser()!!.uid) }
authRepository.getCurrentUser()?,let {
    withContext(Dispatchers.IO) { repository.saveMadeRecipe(recipeId, it.uid) }
}

иначе есть вероятность, что между проверкой и повторным вызовом функции юзер обнулится

многопоточность же

2023-05-17 15:28 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/feed/presentation/FullRecipeFragment.kt
> +            viewModel.saveMadeRecipe(viewModel.currentRecipeState.value.currentRecipe!!.id!!)
на такие гарантии не стоит полагаться, потому что об этой логике знаешь только ты

через год ты уволишься, в компанию придет другой человек, и не уследит, что в этот фрагмент не надо передавать null

достаточно простой проверки viewModel.currentRecipeState.value.currentRecipe?.let { }, чтобы у юзера ничего не крашнулось даже в худшем случае

2023-05-21 16:35 UTC, denisdolgopolov submitted a review, later dismissed

2023-05-21 16:35 UTC, denisdolgopolov commented on app/src/main/java/com/example/kotlinTeam/feed/domain/useCase/SaveMadeRecipeUseCase.kt
> +                withContext(Dispatchers.IO) { repository.saveMadeRecipe(recipeId, authRepository.getCurrentUser()!!.uid) }
результат первого вызова getCurrentUser() не используется

authRepository.getCurrentUser()!!.uid -> it.id

2023-05-22 17:06 UTC, MikeSIOO approved these changes

2023-05-22 20:13 UTC, merged